### ISSUE TITLE
Test updated linkam plan on i22

### ISSUE THREAD

**Issue by abbiemery** [DiamondLightSource/i22-bluesky#27]
There have been a large number of changes to the ophyd-async and dodal libraries since the November linkam experiment. The plan and devices have been brought up to date with regards to syntax, however we have not been able to test the plan runs as expected as the stopflow plan has current priority. 

Once the stopflow experiment has completed, we should go back and ensure the linkam experiment is also functional.

---

Due to moving the Pilatus into ophyd-async, the current Pilatus implementation does not support configuring the Stats plugin as was previously done with the Linkam. This therefore requires https://github.com/bluesky/ophyd-async/issues/213

**Comment by stan-dot** [comment]
doing this on Tuesday 16.07 with @DiamondJoseph

**Comment by stan-dot** [comment]
limited success

**Comment by stan-dot** [comment]
#90 will necessitate further testing

**Comment by stan-dot** [comment]
will try on 17.09

**Comment by stan-dot** [comment]
related

https://github.com/bluesky/ophyd-async/pull/468/files

**Comment by stan-dot** [comment]
this doesn't really seem to belong in the pure software part, closing as not planned - that testing should be tracked elsewhere
