### ISSUE TITLE
Default sensible arguments for plans

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/i22-bluesky#30]
Check with beamline staff which `detectors` should be used by standard on plans: saxs, waxs, oav, i0 & it?

Inject those as a default argument `inject(["saxs", "waxs", ...])`

Inject other sensible defaults such that the minimum set of arguments are `required` in the pydantic schema

**Comment by stan-dot** [comment]
answer that I received:
> SAXS,WAXS,I0, and It
which confirms @DiamondJoseph 's prediction
the PR should add those with `inject`

**Comment by DiamondJoseph** [comment]
SAXS or saxs?

**Comment by stan-dot** [comment]
??? I wasn't aware of the difference between capitalized and lowercase versions, the one relayed to me was ;
SAXS, WAXS, I0, It

**Comment by stan-dot** [comment]
>  used by standard on plans
which plans exactly, @DiamondJoseph ?
should we have a CLI to autogenerate those plans? a plan template?

at the moment both stopflow and linkam plans have multiple devices injected

**Comment by DiamondJoseph** [comment]
> which plans


https://github.com/DiamondLightSource/i22-bluesky/blob/main/src/i22_bluesky/plans/stopflow.py#L59

Yes, these DEFAULT_BASELINE type constants were what I was envisioning when I wrote the ticket. I just don't think I connected this issue to the relevant commits when it was done.
