### ISSUE TITLE
Do not pass panda into the StartDocument metadata "detectors"

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/i22-bluesky#56]
This is used downstream to construct the primary data devices that are expected to have `data` primary fields: the PandA does not provide hints so the primary data set cannot be discerned.

**Comment by DiamondJoseph** [comment]
If this line https://github.com/DiamondLightSource/i22-bluesky/blob/b18e373acf737516bdc94f5343b7cabcc61452e4/src/i22_bluesky/plans/stopflow.py#L111 is moved down to underneath the creation of the metadata, that will accomplish what is required without breaking the internal flow of the plan.

**Comment by callumforrester** [comment]
Fixed by #53
