### ISSUE TITLE
Replace save/load stubs with ophyd_async generic save/loading

### ISSUE THREAD

**Issue by rosesyrett** [DiamondLightSource/i22-bluesky#7]
When https://github.com/bluesky/ophyd-async/pull/63 is merged, ophyd-async will have save/loading which means we can replace what's in this repo with that (or modify it) so as to avoid code duplication.

**Comment by stan-dot** [comment]
```
def get_src_root() -> Path:
    """Path to the root directory of the source code for the project."""
    return Path(__file__).parent.parent.parent

```


not sure what is the desired logic here in ophyd_async
