### ISSUE TITLE
Configure devcontainer plugins

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/i22-bluesky#83]
I think we should keep toml, yaml and python and ruff extensions

_Originally posted by @stan-dot in https://github.com/DiamondLightSource/i22-bluesky/pull/81#discussion_r1672236254_

**Comment by DiamondJoseph** [comment]
Alt wording: configure devcontainer plugins to enable.
I would recommend trying to find a minimal set that you are happy to develop with, without overwhelming anyone trying to contribute.

There will probably be takeaway from this for the generic blueapi dev environment

**Comment by stan-dot** [comment]
toml and yaml are config files and it is straightforward to also add them to the devcontainer

the same goes for python and ruff that are necessary for the repo to work.


That 4 is a minimum set, I don't think that is controversial. Also I don't have anything more that I would like to add
